#ifndef STATES_H
#define STATES_H

enum State {
    CHUA_CO_KET_NOI,
    KET_NOI_BLE,
    CHO_THONG_TIN_WIFI,
    KET_NOI_WIFI,
    NHAN_THONG_TIN_WIFI,
    KET_NOI_WIFI_THANH_CONG,
    GUI_DU_LIEU_MQTT,
    CHE_DO_BLE,
    CHE_DO_LAN,
    CHE_DO_AP, 
    SEND_FLASH_DATA
};

#endif
